# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalstatus',
            options={},
        ),
        migrations.AddField(
            model_name='generalstatus',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reporting.GeneralStatus'),
        ),
        migrations.AddField(
            model_name='generalstatus',
            name='ttl',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='generalstatus',
            name='status',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='generalstatus',
            name='prescription_piece',
        ),
        migrations.AlterUniqueTogether(
            name='generalstatus',
            unique_together=set([('parent', 'content_type')]),
        ),
    ]
