# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reporting', '0002_auto_20170927_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalstatus',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterUniqueTogether(
            name='generalstatus',
            unique_together=set([]),
        ),
    ]
