# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20170928_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalstatus',
            name='date_set',
            field=models.DateTimeField(unique=True),
        ),
    ]
