# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 06:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskASFTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
    ]
