# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import domain.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dasa', models.PositiveIntegerField()),
                ('medinc', models.CharField(max_length=50)),
                ('medinc_description', models.TextField(null=True)),
                ('synonymy', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('cnpj', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], default='NOK', max_length=3)),
                ('cnpj', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=250)),
                ('street_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('lat', models.FloatField(blank=True, help_text='Lat', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Long', null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Lat/Long coordinates', null=True, srid=4326)),
                ('exams', models.ManyToManyField(to='domain.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_plan_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PRE', 'Prescription'), ('SCH', 'Scheduling'), ('ELI', 'Eligible'), ('REJ', 'Rejected'), ('ALT', 'Alternatives given'), ('WAI', 'Waiting'), ('DON', 'Done')], default='PRE', max_length=3)),
                ('doctor_crm', models.CharField(max_length=50)),
                ('lab_expected_time', models.CharField(max_length=250)),
                ('lab_file_code', models.CharField(max_length=250)),
                ('eta_in_minutes', models.PositiveIntegerField()),
                ('picture_insurance_card_front', models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path)),
                ('picture_insurance_card_back', models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path)),
                ('picture_prescription', models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path)),
                ('exams', models.ManyToManyField(to='domain.Exam')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.InsuranceCompany')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_device', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('picture_id', models.ImageField(blank=True, null=True, upload_to=domain.utils.user_data_path)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=domain.utils.user_data_path)),
                ('preferred_laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Patient'),
        ),
    ]
