# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='eta_in_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='lab_expected_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='lab_file_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
