# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20161118_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
