# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20161121_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory'),
        ),
    ]
