# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_laboratory_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('RDI', 'RDI'), ('AC', 'Análises Clínicas')], default='AC', max_length=8),
        ),
    ]
