# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_auto_20161121_0319'),
        ('domain', '0004_auto_20161121_1514'),
    ]

    operations = [
    ]
