# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_merge_20161121_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='Not provided', max_length=300),
            preserve_default=False,
        ),
    ]
