# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_patient_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='eta_in_minutes',
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='doctor_crm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='exams',
            field=models.ManyToManyField(blank=True, null=True, to='domain.Exam'),
        ),
    ]
