# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 01:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_auto_20161121_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.InsuranceCompany'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='insurance_plan_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory'),
        ),
    ]
