# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_auto_20161122_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
