# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_auto_20161122_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_device',
            field=models.TextField(blank=True, null=True),
        ),
    ]
