# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_auto_20161123_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.TextField(),
        ),
    ]
