# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models

import domain.utils


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_auto_20161123_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_id_back',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_id_front',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
    ]
