# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_auto_20161123_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='selfie_id_matches',
            field=models.BooleanField(default=False),
        ),
    ]
