# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_medicalprescription_selfie_id_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
