# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_insurancecompany_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
