# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_auto_20161123_2139'),
        ('domain', '0018_auto_20161124_0111'),
    ]

    operations = [
    ]
