# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0019_merge_20161124_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='state',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='state_abbreviation',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='district',
            field=models.TextField(),
        ),
    ]
