# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0021_auto_20161124_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='suggested_labs',
            field=models.ManyToManyField(blank=True, null=True, related_name='suggested_labs', to='domain.Laboratory'),
        ),
    ]
