# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0024_medicalprescription_lab_expected_time'),
        ('domain', '0023_auto_20161128_1611'),
    ]

    operations = [
    ]
