# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0025_medicalprescription_plan_product_code'),
        ('domain', '0025_merge_20161128_2111'),
    ]

    operations = [
    ]
