# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0026_merge_20161128_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='procedure_average_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='status',
            field=models.CharField(choices=[('PATIENT_REQUESTED', 'Paciente submeteu pedido'), ('EXAMS_IDENTIFIED', 'Exames identificados'), ('ELIGIBLE_LAB', 'Laboratório elegível'), ('ALTERNATIVE_LAB_GIVEN', 'Laboratórios alternativos sugeridos'), ('PATIENT_CANCELED', 'Paciente Cancelou'), ('PROCEDURES_NOT_COVERED', 'Exames não cobertos pelo Plano'), ('LAB_RECORD_OPEN', 'Pré Cadastro criado no laboratório'), ('PROCEDURES_EXECUTED', 'Procedimentos executaods'), ('LAB_RECORD_CANCELED', 'Ficha no laboratório cancelada')], default='PATIENT_REQUESTED', max_length=35),
        ),
    ]
