# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0027_auto_20161129_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='exams',
            field=models.ManyToManyField(blank=True, to='domain.Exam'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='exams',
            field=models.ManyToManyField(blank=True, to='domain.Exam'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='suggested_labs',
            field=models.ManyToManyField(blank=True, related_name='suggested_labs', to='domain.Laboratory'),
        ),
    ]
