# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0028_auto_20161205_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
