# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0029_medicalprescription_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='laboratorybrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='medicalprescription',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created']},
        ),
    ]
