# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0031_tokencreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
