# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0033_recoverpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpassword',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 15, 32, 58, 425701)),
        ),
        migrations.AlterField(
            model_name='recoverpassword',
            name='token',
            field=models.CharField(default='a1ngczaMxGyKuWSh', max_length=16, unique=True),
        ),
    ]
