# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0035_auto_20170322_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpassword',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 16, 46, 10, 552946)),
        ),
        migrations.AlterField(
            model_name='recoverpassword',
            name='token',
            field=models.CharField(default='1e1c52d5cc2849408a3150e6f19c8748', max_length=32, unique=True),
        ),
    ]
