# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0036_auto_20170322_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpassword',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recoverpassword',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
