# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0038_auto_20170327_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Exam')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory')),
            ],
        ),
    ]
