# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import domain.utils


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0039_preparationstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=250)),
                ('result', models.CharField(max_length=150)),
                ('reference_values', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Exam')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.MedicalPrescription')),
            ],
        ),
    ]
