# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0041_auto_20170328_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=250)),
                ('result', models.CharField(max_length=150)),
                ('reference_values', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='description',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='reference_values',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='title',
        ),
        migrations.AddField(
            model_name='examresultdetail',
            name='exam_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.ExamResult'),
        ),
    ]
