# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 19:45
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0043_auto_20170331_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledexam',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
