# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0044_auto_20170331_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='status',
            field=models.CharField(choices=[('PATIENT_REQUESTED', 'Paciente submeteu pedido'), ('EXAMS_IDENTIFIED', 'Exames identificados'), ('EXAMS_ANALYZED', 'Exames analizados para aprovação/reprovação')], default='PATIENT_REQUESTED', max_length=35),
        ),
    ]
