# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0045_auto_20170403_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_scheduled_by_phone',
            field=models.BooleanField(default=False),
        ),
    ]
