# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0048_auto_20170404_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledExamPhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phone', models.BigIntegerField()),
                ('call_time', models.DateTimeField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('scheduled_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domain.ScheduledExam')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
