# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0049_scheduledexamphonecall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='status',
            field=models.CharField(choices=[('PATIENT_REQUESTED', 'Paciente submeteu pedido'), ('EXAMS_IDENTIFIED', 'Exames identificados'), ('EXAMS_ANALYZED', 'Exames analizados para aprovação/reprovação'), ('REQUEST_EXPIRED', 'Prescrição expirou')], default='PATIENT_REQUESTED', max_length=35),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='status',
            field=models.CharField(choices=[('EXAM_IDENTIFIED', 'Exame identificado'), ('ELIGIBLE_PATIENT', 'Paciente elegível'), ('PROCEDURES_NOT_COVERED', 'Exame não cobertos pelo Plano'), ('ALTERNATIVE_LAB_GIVEN', 'Laboratórios alternativos sugeridos'), ('EXAM_TIME_SCHEDULED', 'Paciente agendou horário para o exame'), ('PATIENT_CANCELED', 'Paciente Cancelou'), ('EXAM_EXPIRED', 'Exame estava agendado mas o paciente não compareceu'), ('LAB_RECORD_OPEN', 'Pré Cadastro criado no laboratório'), ('PROCEDURES_EXECUTED', 'Procedimento executado'), ('LAB_RECORD_CANCELED', 'Ficha no laboratório cancelada'), ('RESULTS_RECEIVED', 'Resultado do exame está pronto')], default='EXAM_IDENTIFIED', max_length=35),
        ),
    ]
