# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0054_scheduledexam_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
