# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0055_patient_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
