# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0057_auto_20170419_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
