# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0058_laboratoryfacilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryOpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('week_day', models.CharField(choices=[('Dom', 'Domingo'), ('Seg', 'Segunda-feira'), ('Seg', 'Terça-feira'), ('Seg', 'Quarta-feira'), ('Seg', 'Quinta-feira'), ('Seg', 'Sexta-feira'), ('Seg', 'Sábado')], max_length=13)),
                ('is_open', models.BooleanField(default=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Laboratory')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
