# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0061_auto_20170424_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryopeninghours',
            name='week_day',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
