# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 16:53
from __future__ import unicode_literals

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0063_auto_20170426_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
