# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 16:57
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Patient = apps.get_model('domain', 'Patient')
    for row in Patient.objects.all():
        row.hash = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0064_patient_hash'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
