# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0068_auto_20170427_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.InsuranceCompany')),
                ('laboratories', models.ManyToManyField(blank=True, null=True, to='domain.Laboratory')),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='HealthInsurancePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=50)),
                ('health_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.HealthInsurance')),
            ],
            options={
                'ordering': ['plan_code'],
            },
        ),
    ]
