# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0069_healthinsurance_healthinsuranceplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='insurance_plan_code',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='health_insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.HealthInsurancePlan'),
        ),
    ]
