# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0070_auto_20170428_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorybrand',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
