# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0073_auto_20170504_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsuranceplan',
            name='plan_code',
            field=models.CharField(max_length=250),
        ),
    ]
