# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0074_auto_20170504_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationstep',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='preparationstep',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
