# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0075_auto_20170504_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='exams_not_registered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
