# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0078_auto_20170511_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
