# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0079_medicalprescription_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
