# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0080_medicalprescription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationstep',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
