# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0083_scheduledexam_results_expected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='lab_file_code',
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='lab_file_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
