# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import domain.utils


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0084_auto_20170516_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='picture',
        ),
        migrations.AddField(
            model_name='examresult',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=domain.utils.exam_result_path),
        ),
    ]
