# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0085_auto_20170516_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexam',
            name='results_expected_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
