# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0087_auto_20170518_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='prescription_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
