# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import domain.utils


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0089_auto_20170526_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_id_back_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_id_front_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_insurance_card_back_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_insurance_card_front_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='picture_prescription_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='selfie_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.prescription_path),
        ),
        migrations.AddField(
            model_name='patient',
            name='picture_id_back_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.user_data_path),
        ),
        migrations.AddField(
            model_name='patient',
            name='picture_id_front_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.user_data_path),
        ),
        migrations.AddField(
            model_name='patient',
            name='selfie_uploadcare',
            field=models.ImageField(blank=True, null=True, upload_to=domain.utils.user_data_path),
        ),
    ]
