# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0089_auto_20170526_2248'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='preparationstep',
            index_together=set([('exam', 'laboratory')]),
        ),
    ]
