# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0090_auto_20170627_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorybrand',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
