# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0092_auto_20170627_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='status',
            field=models.CharField(choices=[('PATIENT_REQUESTED', 'Paciente submeteu pedido'), ('EXAMS_IDENTIFIED', 'Exames identificados'), ('UNREADABLE_PICTURES', 'Imagem da prescrição está ilegível'), ('NOT_REGISTERED_EXAMS_FOUND', 'Há exame(s) não contemplado(s) pelo Sara'), ('EXAMS_ANALYZED', 'Exames analizados para aprovação/reprovação'), ('REQUEST_EXPIRED', 'Prescrição expirou'), ('PICTURES_ID_SELFIE_DONT_MATCH', 'Imagens do documento e selfie não são correspondentes')], db_index=True, default='PATIENT_REQUESTED', max_length=150),
        ),
        migrations.AlterIndexTogether(
            name='medicalprescription',
            index_together=set([('created', 'status')]),
        ),
    ]
