# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0094_auto_20170627_0215'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='recoverpassword',
            index_together=set([('user', 'is_used')]),
        ),
    ]
