# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0095_auto_20170627_0223'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='scheduledexam',
            index_together=set([('scheduled_time', 'status'), ('exam', 'status'), ('prescription', 'exam'), ('prescription', 'status'), ('laboratory', 'prescription')]),
        ),
    ]
