# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0096_auto_20170627_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationstep',
            name='start_preparation_in_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
