# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0098_auto_20170630_1510'),
        ('domain', '0098_auto_20170629_1250'),
    ]

    operations = [
    ]
