# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0099_merge_20170703_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
