# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-04 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0100_holiday_description'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='holiday',
            index_together=set([('country', 'state', 'city')]),
        ),
    ]
