# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0090_auto_20170605_1332'),
        ('domain', '0101_auto_20170704_1516'),
    ]

    operations = [
    ]
