# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0102_medicalprescription_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
