# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0103_auto_20170717_0213'),
        ('domain', '0102_merge_20170705_1741'),
    ]

    operations = [
    ]
