# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models, transaction
import django.db.models.deletion
import django_extensions.db.fields

from domain.models import MedicalPrescription, PrescriptionPiece, ScheduledExam
from domain import utils


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0107_medicalprescription_period_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('annotations', models.TextField(blank=True, null=True)),
                ('doctor_crm', models.CharField(blank=True, max_length=50, null=True)),
                ('exams_not_registered', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('prescription_issued_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.MedicalPrescription')),
                ('picture', models.ImageField(blank=True, null=True,
                                              upload_to=utils.prescription_path_for_prescription_piece)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='prescription_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.PrescriptionPiece'),
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='is_grouped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionpiece',
            name='status',
            field=models.CharField(choices=[('PIECE_CREATED', 'Pedaço de prescrição criado'),
                                            ('REQUEST_EXPIRED', 'Pedaço de prescrição expirou')], db_index=True,
                                   default='PIECE_CREATED', max_length=150),
        ),
    ]
