# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0108_auto_20170815_0317'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='scheduledexam',
        #     name='prescription_piece',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.PrescriptionPiece'),
        #     preserve_default=False,
        # ),
    ]
