# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0110_auto_20170815_0359'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='scheduledexam',
        #     name='prescription_piece',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exams', to='domain.PrescriptionPiece'),
        # ),
    ]
