# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0111_auto_20170815_1414'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='prescriptionpiece',
        #     old_name='issued_at',
        #     new_name='prescription_issued_at',
        # ),
    ]
