# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0112_auto_20170817_1647'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='prescriptionpiece',
        #     name='status',
        #     field=models.CharField(choices=[('PIECE_CREATED', 'Pedaço de prescrição criado'), ('REQUEST_EXPIRED', 'Pedaço de prescrição expirou')], db_index=True, default='PIECE_CREATED', max_length=150),
        # ),
    ]
