# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-11 11:57
from __future__ import unicode_literals

from django.db import migrations


REJECTED_PIECE_NO_STAMP = 'REJECTED_PIECE_NO_STAMP'
REJECTED_PIECE_NO_CRM = 'REJECTED_PIECE_NO_CRM'
REJECTED_PIECE_NO_SIGNATURE = 'REJECTED_PIECE_NO_SIGNATURE'
REJECTED_PIECE_CROPPED = 'REJECTED_PIECE_CROPPED'
REJECTED_PIECE_BAD_CALLIGRAPHY = 'REJECTED_PIECE_BAD_CALLIGRAPHY'
REJECTED_PIECE_ERASURE = 'REJECTED_PIECE_ERASURE'
REJECTED_PIECE_MULTIPLE_COLORS = 'REJECTED_PIECE_MULTIPLE_COLORS'
REJECTED_PIECE_NOT_IN_INSURANCE_RULES = 'REJECTED_PIECE_NOT_IN_INSURANCE_RULES'
REJECTED_PIECE_NOT_A_PRESCRIPTION = 'REJECTED_PIECE_NOT_A_PRESCRIPTION'
REJECTED_PIECE_UNREADABLE_IMAGE = 'REJECTED_PIECE_UNREADABLE_IMAGE'

REJECTED_PRESCRIPTION_PICTURES_ID_SELFIE_DONT_MATCH = 'REJECTED_PRESCRIPTION_PICTURES_ID_SELFIE_DONT_MATCH'
REJECTED_PRESCRIPTION_INVALID_HEALTH_CARD_PIC = 'REJECTED_PRESCRIPTION_INVALID_HEALTH_CARD_PIC'
REJECTED_PRESCRIPTION_INVALID_ID_PIC = 'REJECTED_PRESCRIPTION_INVALID_ID_PIC'
REJECTED_PRESCRIPTION_NOT_A_PRESCRIPTION_PACKAGE = 'REJECTED_PRESCRIPTION_NOT_A_PRESCRIPTION_PACKAGE'

STATUS_CHOISES = (
        (REJECTED_PIECE_NO_STAMP, 'Carimbo não está visível'),
        (REJECTED_PIECE_NO_CRM, 'CRM não está visível'),
        (REJECTED_PIECE_NO_SIGNATURE, 'Assinatura não está visível'),
        (REJECTED_PIECE_CROPPED, 'A imagem está cortada'),
        (REJECTED_PIECE_BAD_CALLIGRAPHY, 'Escrita ilegível'),
        (REJECTED_PIECE_ERASURE, 'Apresenta rasuras'),
        (REJECTED_PIECE_MULTIPLE_COLORS, 'Mais de uma cor de caneta'),
        (REJECTED_PIECE_NOT_IN_INSURANCE_RULES, 'Fora das regras do convênio'),
        (REJECTED_PIECE_NOT_A_PRESCRIPTION, 'Não é uma prescrição'),
        (REJECTED_PIECE_UNREADABLE_IMAGE, 'Imagem ilegível'),

        (REJECTED_PRESCRIPTION_PICTURES_ID_SELFIE_DONT_MATCH, 'Pessoa da selfie difere do documento'),
        (REJECTED_PRESCRIPTION_INVALID_HEALTH_CARD_PIC, 'Fotos inválidas da carteirinha'),
        (REJECTED_PRESCRIPTION_INVALID_ID_PIC, 'Fotos inválidas do documento'),
        (REJECTED_PRESCRIPTION_NOT_A_PRESCRIPTION_PACKAGE, 'Não há um pedido médico no envio'),
    )

FEEDBACK = {
    REJECTED_PIECE_NO_STAMP: 'O pedido não apresenta o carimbo do médico.',
    REJECTED_PIECE_NO_CRM: 'O pedido não apresenta o CRM do médico.',
    REJECTED_PIECE_NO_SIGNATURE: 'O pedido não apresenta a assinatura do médico.',
    REJECTED_PIECE_CROPPED: 'A imagem está cortada e esconde informações do pedido.',
    REJECTED_PIECE_BAD_CALLIGRAPHY: 'A caligrafia no pedido de exames está ilegível.',
    REJECTED_PIECE_ERASURE: 'O pedido apresenta rasuras.',
    REJECTED_PIECE_MULTIPLE_COLORS: 'Seu plano de saúde não aceita que o pedido seja escrito com mais de uma cor de caneta.',
    REJECTED_PIECE_NOT_IN_INSURANCE_RULES: 'Seu plano de saúde não aceita o modo como os exames foram descritos.',
    REJECTED_PIECE_NOT_A_PRESCRIPTION: 'A imagem enviada não é um pedido médico.',
    REJECTED_PIECE_UNREADABLE_IMAGE: 'A imagem está ilegível.',
    REJECTED_PRESCRIPTION_PICTURES_ID_SELFIE_DONT_MATCH: 'A selfie que você enviou está muito diferente da foto do seu documento.',
    REJECTED_PRESCRIPTION_INVALID_HEALTH_CARD_PIC: 'As fotos da sua carteirinha não parecem estar certas.',
    REJECTED_PRESCRIPTION_INVALID_ID_PIC: 'As fotos do seu documento não parecem estar certas.',
    REJECTED_PRESCRIPTION_NOT_A_PRESCRIPTION_PACKAGE: 'No seu envio não havia nenhuma imagem de pedido médico.',
}

INSTRUCTION = {
    REJECTED_PIECE_NO_STAMP: 'Peça ao seu médico um novo pedido, carimbado.',
    REJECTED_PIECE_NO_CRM: 'Peça ao seu médico um novo pedido, com seu CRM.',
    REJECTED_PIECE_NO_SIGNATURE: 'Peça ao seu médico um novo pedido, assinado.',
    REJECTED_PIECE_CROPPED: 'Envie uma nova foto do pedido completo, sem cortar nenhuma informação.',
    REJECTED_PIECE_BAD_CALLIGRAPHY: 'Peça ao seu médico um novo pedido, com uma caligrafia mais cuidadosa.',
    REJECTED_PIECE_ERASURE: 'Peça ao seu médico um  novo pedido, sem rasuras ou marcas que comprometam a leitura.',
    REJECTED_PIECE_MULTIPLE_COLORS: 'Peça ao seu médico um novo pedido, avise-o de que seu plano de saúde não aceita várias cores de caneta.',
    REJECTED_PIECE_NOT_IN_INSURANCE_RULES: 'Ligue para o seu plano de saúde para entender como o seu médico deverá escrever o pedido de exame.',
    REJECTED_PIECE_NOT_A_PRESCRIPTION: 'Confira se a imagem enviada é mesmo a foto de um pedido de exames feito por seu médico.',
    REJECTED_PIECE_UNREADABLE_IMAGE: 'Envie uma nova imagem do pedido de exame. Certifique-se de que não esteja embassada, tremida ou escura.',
    REJECTED_PRESCRIPTION_PICTURES_ID_SELFIE_DONT_MATCH: 'Confira se o seu documento está atualizado com uma foto que me permita te reconhecer.',
    REJECTED_PRESCRIPTION_INVALID_HEALTH_CARD_PIC: 'Verifique cuidadosamente as fotos de sua carteirinha antes de enviá-los.',
    REJECTED_PRESCRIPTION_INVALID_ID_PIC: 'Verifique cuidadosamente as fotos de seus documentos antes de enviá-los.',
    REJECTED_PRESCRIPTION_NOT_A_PRESCRIPTION_PACKAGE: 'Confira se as imagens enviadas são mesmo as fotos do pedido de exames feito por seu médico.',

}


def add_reasons(apps, schema_editor):
    RejectionReason = apps.get_model('domain', 'RejectionReason')
    data = []
    for reason in STATUS_CHOISES:
        data.append(RejectionReason(
            status=reason[0],
            feedback=FEEDBACK.get(reason[0]),
            instruction=INSTRUCTION.get(reason[0]),
        ))
    RejectionReason.objects.bulk_create(data)


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0114_auto_20170911_1157'),
    ]

    operations = [
        migrations.RunPython(add_reasons),
    ]

