# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0115_auto_20170911_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectionreason',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='rejectionreason',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
