# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:01
from __future__ import unicode_literals

from django.db import migrations


def set_order(apps, schema_editor):
    RejectionReason = apps.get_model('domain', 'RejectionReason')
    i = 0
    for reason in RejectionReason.objects.all():
        reason.sort_order = i
        reason.save()
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0116_auto_20170915_1132'),
    ]

    operations = [
        migrations.RunPython(set_order),
    ]
