# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0117_auto_20170915_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='sort_order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
