# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0119_auto_20170918_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionpiece',
            options={'ordering': ['pk']},
        ),
    ]
