# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0120_laboratorybrand_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationstep',
            name='recent_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
