# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0121_preparationstep_recent_description'),
        ('domain', '0120_auto_20170927_1030'),
    ]

    operations = [
    ]
