# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0122_merge_20170928_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexamphonecall',
            name='attempt',
            field=models.SmallIntegerField(default=0),
        ),
    ]
