# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0123_scheduledexamphonecall_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='results_arrived_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='lab_file_code',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
