# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0125_scheduledexam_results_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='einstein_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='einstein_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lavoisier_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lavoisier_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
