# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0126_auto_20171208_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='health_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.HealthInsurance'),
        ),
    ]
