# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0128_auto_20171216_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='einstein_pass',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='einstein_user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lavoisier_pass',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lavoisier_user',
        ),
        migrations.RemoveField(
            model_name='scheduledexam',
            name='results_completed_at',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='laboratory_brands',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
