# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_zendeskasfticket'),
        ('domain', '0130_auto_20180201_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='zendesk_adf_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2m.ZendeskASFTicket'),
        ),
    ]
