# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0131_scheduledexam_zendesk_adf_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='status',
            field=models.CharField(choices=[('PATIENT_REQUESTED', 'Paciente submeteu pedido'), ('EXAMS_IDENTIFIED', 'Exames identificados'), ('UNREADABLE_PICTURES', 'Imagem da prescrição está ilegível'), ('NOT_REGISTERED_EXAMS_FOUND', 'Há exame(s) não contemplado(s) pelo Sara'), ('EXAMS_ANALYZED', 'Exames analizados para aprovação/reprovação'), ('REQUEST_EXPIRED', 'Prescrição expirou'), ('PICTURES_ID_SELFIE_DONT_MATCH', 'Imagens do documento e selfie não são correspondentes'), ('PACKAGE_REJECTED', 'Prescrição rejeitada'), ('PATIENT_CANCELED_BY_CALL', 'Cancelado pelo paciente por telefone'), ('PHONECALL_NOT_ANSWERED', 'Ligação não atendida'), ('PICTURES_HEALTHCARD_ID_DONT_MATCH', 'Fotos inválidas do plano'), ('INVALID_HEALDH_CARD_PICTURE', 'Fotos da Carteirinha do plano inválidas'), ('INVALID_ID_PICTURE', 'Fotos da identidate inválida'), ('NOT_A_PRESCRIPTION', 'Imagens da prescição ilegíveis'), ('PROCEDURES_NOT_COVERED', 'Procedimentos não cobertos pelo plano')], db_index=True, default='PATIENT_REQUESTED', max_length=150),
        ),
    ]
