# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |bradesco_config|
  # Every Vagrant virtual environment requires a box to build off of.
  bradesco_config.vm.box = "vivid64"

  # The URL from where the 'bradesco_config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  bradesco_config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/vivid/current/vivid-server-cloudimg-amd64-vagrant-disk1.box"

  # Configure virtual machine specs. Keep it simple, single user.
  bradesco_config.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", 2048]
    p.customize ["modifyvm", :id, "--cpus", 2]
    p.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
  end

  # Configure a synced folder between HOST and GUEST
  bradesco_config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", :mount_options => ["dmode=777","fmode=777"]
  bradesco_config.vm.synced_folder "../../backend/", "/var/www/backend", id:"backend-root", :mount_options => ["dmode=777","fmode=777"]
  bradesco_config.vm.synced_folder "../../frontend", "/var/www/frontend", id:"fontend-root", :mount_options => ["dmode=777","fmode=777"]

  # Config hostname and IP address so entry can be added to HOSTS file
  bradesco_config.vm.hostname = "vagrant"
  bradesco_config.vm.network :private_network, ip: '192.168.99.100'

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  bradesco_config.vm.network "forwarded_port", guest: 80, host: 8080
  bradesco_config.vm.network "forwarded_port", guest: 6379, host: 6379
  bradesco_config.vm.network "forwarded_port", guest: 8000, host: 8000
  bradesco_config.vm.network "forwarded_port", guest: 8889, host: 8889

  # kickoff a shell script to install Python essentials
  bradesco_config.vm.provision :shell, path: "vagrant_bootstrap.sh"
end
